<?php include('header.php'); ?>
<body id="about" class="white">
  <?php include('menu.php'); ?>
  <section id="about-hero" class="flex">
    <div id="about-hero-intro">
      <h1>Our Shared Vision</h1>
      <a id="about-video" href="#video" onclick="playVid()"><?php echo file_get_contents("images/svg-play.svg"); ?></a>
    </div>
    <div id="video" class="overlay-video">
      <div class="popup">
        <a class="close" href="#" onclick="pauseVid()">&times;</a>
        <div class="content">
          <h3>Chasing Dreams, Changing Destinies</h3>
          <video id="mafi-video-file" width="100%" height="400" controls>
            <source src="mafi-video.m4v" type="video/mp4" autoplay>
            Your browser does not support the video tag.
          </video>
        </div>
      </div>
    </div>
    <div class="overlay"></div>
  </section>
  <section id="about-vm" class="flex green">
    <div class="container flex">
      <div>
        <h5>Our Collective Vision</h5>
        <h3>Mount Apo Foundation, Inc. empowers the indigenous tribes and other upland dwellers surrounding Mount Apo for the protection and preservation of their environment and culture, allowing them to sustainably prosper far into the future.</h3>
      </div>
      <div>
        <h5>Our Corporate Mission</h5>
        <h3>Empowered upland dwellers and IP communities, capable of self-direction, and working together in unity and harmony towards achieving the sustained conservation of biodiversity and ecosystem of Mount Apo, and preserving their traditionally-based aspirations, values, and way of life.</h3>
      </div>
    </div>
    <?php echo file_get_contents("images/svg-horizon.svg"); ?>
  </section>
  <section id="about-values">
    <div id="values" class="flex">
      <div><h3> Pro-IP</h3>
        <?php echo file_get_contents("images/icon-culture.svg"); ?>
      </div>
      <div><h3>Pro-Environment</h3>
        <?php echo file_get_contents("images/icon-envi.svg"); ?>
      </div>
      <div><h3>Pro-Education</h3>
        <?php echo file_get_contents("images/icon-educ.svg"); ?>
      </div>
    </div>
    <div id="about-history" class="two-col">
      <div>
        <p>Mount Apo Foundation, Inc. (MAFI) was born out of the Environmental Compliance Certificate (ECC) requirement for the operation of the Mt. Apo Geothermal Power Plants in 1992. The ECC required the establishment of an Environmental and Tribal Welfare Trust Fund (ETWTF) to uplift upland dwellers and preserve the ecosystem of Mt. Apo where the Mt. Apo Geothermal Power Plant operates. The ETWTF gets one centavo per kilowatt-hour of electric power generated by the Mt. Apo Geothermal Power Plants and is governed by MAFI’s Board of Trustees comprising representatives from Energy Development Corporation (EDC) who own and operate the Mt. Apo Geothermal Power Plants, Department of Environment and Natural Resources (DENR), Department of Energy (DOE), Cotabato Tribal Consultative Council for Development, Inc. (CTCCDI), Local Government Units from the host province of Cotabato, host city of Kidapawan, and host Barangay Ilomavis, and a people’s organization.</p>
        <p>In it’s over 25 years of existence MAFI has established and nurtured relationships with 33 barangays in the Mt. Apo Natural Park that resulted into over 320 college graduates, over 9,441 IP members finishing adult literacy programs, 13 has. of reforested areas and a number of partners. With MAFI’s experience, it is poised to grow and pursue its mission and vision through multi-stakeholders’ partnerships.
        </p>
      </div>
      <ul class="link-list">
        <h3>Learn More</h3>
        <li><a href="milestones.php" class="button">Milestones <?php echo file_get_contents("images/svg-arrow.svg"); ?></a></li>
        <li><a class="button" onclick="scrollToTargetAdjusted('about-ar');">Annual Reports <?php echo file_get_contents("images/svg-arrow.svg"); ?></a></li>
        <li><a class="button" onclick="scrollToTargetAdjusted('bot');">Board of Trustees  <?php echo file_get_contents("images/svg-arrow.svg"); ?></a></li>
        <li><a class="button" onclick="scrollToTargetAdjusted('about-partners');">Partners <?php echo file_get_contents("images/svg-arrow.svg"); ?></a></li>
      </ul>
    </div>
    <div id="recent-milestones">
      <div class="section-heading">
        <h3>Recent Milestones</h3>
        <a href="milestones.php" class="button dark-beige-text">VIEW ALL</a>
      </div>
      <div id="mile-divider">
        <div id="mile-divider-circle"></div>
      <?php echo file_get_contents("images/svg-mile-line.svg"); ?></div>
      <div class="mile-grid">
        <div class="mile-item">
          <img src="images/photo-4.png">
          <div class="mile-info">
            <h4>November 2020</h4>
            <p>MAFI’s accreditation application as official NGO partner in the Province of Cotabato was approved.</p>
          </div>
        </div>
        <div class="mile-item">
          <img src="images/photo-4.png">
          <div class="mile-info">
            <h4>September 2020</h4>
            <p>Initiated the process of redesigning the MAFI website through the assistance of the Works of Heart Creatives, Inc., to carry the new brand of the foundation and to better promote MAFI for resource mobilization.</p>
          </div>
        </div>
        <div class="mile-item">
          <img src="images/photo-4.png">
          <div class="mile-info">
            <h4>August 2020</h4>
            <p>Soap Making Project was initiated as a concrete response of MAFI to COVID-19 pandemic as a platform to raise awareness on the importance of handwashing to protect against the virus, to promote MAFI as a foundation, and to raise funds for community livelihood support.</p>
          </div>
        </div>
      </div>
    </div>
  </section>
  <section id="about-ar" class="light-beige center-title">
    <div class="section-title">
      <h1>Annual Reports</h1>
      <h4 class="dark-beige-text">Read our publications to learn more about MAFI ‘s work through the years</h4>
    </div>
    <ul id="pub-list">
      <li><h3>Annual Report 2020</h3>
        <div class="pub-info">
          <h5 class="dark-beige-text">PDF</h5>
          <h5 class="dark-beige-text">0.0KB</h5>
          <a href="" class="button">DOWNLOAD</a>
        </div>
      </li>
      <li><h3>Annual Report 2019</h3>
        <div class="pub-info">
          <h5 class="dark-beige-text">PDF</h5>
          <h5 class="dark-beige-text">0.0KB</h5>
          <a href="" class="button">DOWNLOAD</a>
        </div>
      </li>
      <li><h3>Annual Report 2018</h3>
        <div class="pub-info">
          <h5 class="dark-beige-text">PDF</h5>
          <h5 class="dark-beige-text">0.0KB</h5>
          <a href="" class="button">DOWNLOAD</a>
        </div>
      </li>
      <li><h3>Annual Report 2017</h3>
        <div class="pub-info">
          <h5 class="dark-beige-text">PDF</h5>
          <h5 class="dark-beige-text">0.0KB</h5>
          <a href="" class="button">DOWNLOAD</a>
        </div>
      </li>
      <li><h3>Annual Report 2016</h3>
        <div class="pub-info">
          <h5 class="dark-beige-text">PDF</h5>
          <h5 class="dark-beige-text">0.0KB</h5>
          <a href="" class="button">DOWNLOAD</a>
        </div>
      </li>
    </ul>
    <a href="publications.php" class="button center-text dark-beige-text">VIEW ALL PUBLICATIONS</a>
  </section>
  <section id="bot" class="dark-beige center-title">
    <div class="section-title">
      <h1>Board of Trustees</h1>
      <p>The foundation is a non-stock, non-profit corporation with nine-member board of trustees which acts as the policy-making body of the foundation. The board of trustees is composed of various sectors coming from the local government units, indigenous/tribal people, national government agencies and corporation and non-government organization.</p>
    </div>
    <?php include('bot.php'); ?>
  </section>
  <section id="about-partners" class="beige center-title center-text">
    <div class="section-title">
      <h1>Our Partners</h1>
    </div>
    <div id="partners-list">
      <h3>The Multi-Sectoral Management Group (MSMG)/Founding Members</h3>
      <br/>
      <img src="images/home-partners-logos.png">
      <br/><br/><br/><br/><br/>
      <h3>Accrediting and Regulatory Agencies</h3>
      <br/>
      <img src="images/ara-logos.png">
      <br/><br/><br/><br/><br/>
      <h3>Partners in the Area of Responsibility </h3>
      <br/>
      <img src="images/par-logos.png">
      <br/><br/><br/><br/><br/>
      <h3>Donors, Benefactors & Volunteer Groups (2019 Earthquake Calamity)</h3>
      <br/>
      <img src="images/dbv-logos.png">
      <br/><br/>
      <p>MOCOMEA, Inc. (Misamis Oriental)<br/>
        Givest<br/>
        Zuellig Pharma<br/>
        High Temp Industrial Corp.<br/>
        South Cotabato Dental Society<br/>
        Porticus Resto Bar<br/>
        Kidapawan Musicians Club<br/>
        39th Infantry Brigade, AFP<br/>
        Kidapawan IP Deputy Mayor’s Office<br/>
        ICON-SP<br/>
        GenSan Educators Mountaineering Society<br/>
        Kilusang Pagbabago<br/>
        Kalumad<br/>
        GenSan Team<br/>
        People of South Cotabato<br/>
        People of Pres. Roxas<br/><br/>
      Countless Friends and Individuals Locally, Nationally, and Internationally who donated during the 2019 Earthquake Calamity and rendered their voluntary services</p>
      <br/><br/><br/>
      <h3>Other Partners</h3>
      <br/>
      <p>Kasilak Development Foundation, Inc.<br/>
        Philippine National Bank<br/>
        Obo Manobo Active Language Resource and Community Development, Inc. (OMALRACDI)<br/>
        Works of Heart Creatives, Inc.<br/>
        Philippine Business for Social Progress (PBSP) through Ms. Virgie Ongkiko (Consultant)<br/>
        Balagot & Company CPA's<br/>
        Mahintana Foundation, Inc.<br/>
        Carlos/Valdes & Associates<br/>
        Kapwa Upliftment Foundation<br/>
        Philippine Eagle Foundation, Inc.<br/>
        UP Mindanao<br/>
        Mount Apo Foundation, Inc. Assisted Secondary Schools Association (MAFI ASSA)<br/>
        MAFI Graduate Society (MGS)<br/>
        MAFI Parents-Scholars Organization (MAPSO)<br/>
        Guardians of Lake Venado<br/>
        Protected Area Management Board (PAMB) – Mt. Apo Natural Park<br/>
        Kidapawan Federation of Tribal Chieftains (KFTC)<br/>
        Tuklas Katotobo<br/>
        Kidapawan Central Marketing Corp.<br/>
        A.J. High Time Hotel and Restaurant<br/>
      </p>
    </div>
  </section>
  <footer>
    <div id="footer-cta" style="background-image: url(images/banner-cta-1.png)">
      <div class="footer-cta-content">
        <?php echo file_get_contents("images/icon-0-educ.svg"); ?>
        <h2>Contribute to the cause</h2>
        <a href="getinvolved.php" class="button">GET INVOLVED <?php echo file_get_contents("images/svg-arrow.svg"); ?></a>
      </div>
      <?php echo file_get_contents("images/svg-footer-cta-bg.svg"); ?>
      <div class="overlay"></div>
    </div>
    <?php include('footer.php'); ?>